### ISSUE TITLE
4 Лаба Код

### ISSUE THREAD

**Issue by oleg-tgn** [Romania322/OAIP_labs_Ovanesyan#10]
1) называйте функции более равщернуто

int replace(int stop, char *text);
int lenght(FILE *File);
int readit(int stop, char *text, FILE *SourceFile);

replace - замена чего?
lenght - длина с опечаткой, но блина чего
readit - это вообще что?

2) первым словом в имени функции должен идти глагол
getStringLength
replaceSpacesInString

и тому подобное

3) Source.cpp - переименовать

4) Это из главной функции логично будет вынести в отдельную, которая выводит данные в файл
```
for (int i = 0; i < stop; i++)
	{
		fprintf(NewFile, "%c", text[i]);
	}
```

5) `stop` - странное имя для переменная, которая хранит длину строки. может лучше назвать ее `длинаСтроки`? 
Всегда думайте о том что Вы пишите код не только для себя, а что потом его будут читать другие люди

Или хотите цитату "Пишите код так, как будто сопровождать его будет склонный к насилию психопат, который знает, где вы живёте" Martin Golding (хотя авторство фразы этой приписывают разным людям, точно выяснить не удается)

6) Проще и понятнее тут использовать while
А цикл for оставить для ситуаций, когда нам заранее точно известно число шагов. Хоть Си и позволяет делать иначе, лучше придерживаться такого правила
```
for (int i = 0; fgetc(SourceFile) != EOF; i++)
	{
		stop = stop + 1;
	}
```

7) вот тут вместо модификации переданной переменой было бы лучше отдать считанные значения через return
```
int readit(int stop, char *text, FILE *SourceFile)
{
	int i;
	for (i = 0; i < stop; i++)
	{
		text[i] = fgetc(SourceFile);
	}
	return 0;
}
```

8) Чезчур сложно. Надо переделать
```
int replace(int stop, char *text)
{
	char buff;
	int k = 0;

	for (int i = 1; text[i] != '\0'; i++)
	{
		if (text[i] == ' ' || text[i] == '\n')
		{
			k = i + 1;
		}
		if ((text[i + 1] == ' ' || text[i + 1] == '\n' || i == stop - 1) && text[k] != ' ')
		{
			buff = text[k];
			text[k] = text[i];
			text[i] = buff;
		}
	}
	return 0;
}
```

а за сложностью мы как раз теряем из виду ошибки

пусть дана строк "1 2" мы увидели пробел в этой строке, подменили на следующий символ
а разве строка от этого стала короче?
"122"

**Comment by Romania322** [comment]
Все исправил. Там где вы сказали, что сложно, исправлять я думаю не стоит потому что там много проверок на введение лишних пробелов и прочего. К примеру если между словами будет 2,3,4..пробела)
