### ISSUE TITLE
5 Лаба Код

### ISSUE THREAD

**Issue by oleg-tgn** [Romania322/OAIP_labs_Ovanesyan#12]
1) Source.cpp - переименовываем

2) Шапка с подписью какой это студент, вариант, задание

3) `#include "locale"	//chto za hren' tut tipo iz C++` - это плохо

4) `#pragma warning(disable : 4996)	//bez jetogo u menja oshibka` - разбиритесь в своих ошибках

5) Теперь человек, который работает с Вашим кодом всегда будет смотреть на комментарий, чем N от Y отличается
```
#define N 1000	//dlinna massivov v strukturah
#define Y 100	//kolichestvo struktur
```

называйте константы нормально, вместо написания к ним комментариев

6) `Mag` - дайте полное имя для структуры

7) `//struktura koroch` - это плохо

8) Не должно быть глобальных массивов
`
Gos[Y];
`

9) Называйте переменные полностью, без сокращений

`
Gos[Y];
`
10) Первая буква в переменной - в нижнем регистре

11) 
```
void INPUT(int k);
void OUTPUT(int p);
int INITIALIZATION();
```

Не должно быть названий функций в верхнем регистре, только константы в верхнем регистре.
А так же функция в своем названии должна полностью отражать что она выполняет

12) `void obmen(struct Mag &Gos1, struct Mag &Gos2);` - какой-то странный формат передачи данных

13) `number_of_structures` - такое именование переменных не годится

Итого...

Пока дальше код читать невозможно. Меняйте, правьте, приводите в порядок....

Пока авансом 1/4 за наличие

**Comment by Romania322** [comment]
исправил
