### ISSUE TITLE
Добавьте .gitignore

### ISSUE THREAD

**Issue by oleg-tgn** [Romania322/OAIP_labs_Ovanesyan#2]
1) Сначала прочитать зачем нужен гитигнор есть ссылка на книгу на сайте git-scm на русском
вот глава про гитигнор https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9

2) сам файл гитигнора можно скопировать у меня в репозитории и поместить в свой
https://github.com/oleg-tgn/for-students

**Comment by Romania322** [comment]
Добавил
