### ISSUE TITLE
Создавайте пустым проектом

### ISSUE THREAD

**Issue by oleg-tgn** [Romania322/OAIP_labs_Ovanesyan#4]
Если при создание в VS выбирать пустой проект (Empty Project) не будет появляться излишнего кода и создаваться ненужны файлы

```
#include "stdafx.h"

int _tmain(int argc, _TCHAR* argv[])
```

первой строчки вообще не будет

а функцию сможете написать сами короче

```
int main() {
}
```

**Comment by Romania322** [comment]
Исправил
