### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by oleg-tgn** [Romania322/OAIP_labs_Ovanesyan#8]
А где код?

**Comment by Romania322** [comment]
Закинул

**Comment by oleg-tgn** [comment]
Хорошо

1) Кодировки

2) Сделайте отдельные функции для [проверки корректности ввода](https://github.com/oleg-tgn/for-students/wiki/%D0%9C%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B)

3) Просмотрите еще разок требования, я там немного обновил

4) Отчет есть?

**Comment by Romania322** [comment]
Отчета пока нет. А что за требования и где их смотреть?

**Comment by oleg-tgn** [comment]
[КАК не знаете?](https://github.com/oleg-tgn/for-students/wiki)

**Comment by oleg-tgn** [comment]
Оставил комментарии в коммите

https://github.com/Romania322/OAIP_labs_Ovanesyan/commit/cf8342db5c31d940d2a558ff5f5787078cff68e5
